# Do not change version. This is the version of aws buildspec, not the version of your buldspec file. 
version: 0.2 
phases: 
  install: 
    runtime-versions: 
      nodejs: 10   
    commands: 
      - echo "Change directory to client"
      - cd client
      - echo Installing Mocha... 
      - npm install -g mocha 
      - echo Removing package-lock.json
      - \rm -rf package-lock.json
  pre_build: 
    commands: 
      - echo Installing source NPM dependencies... 
      - npm install 
      - npm install -g @angular/cli@8.3.20
      - echo Installing angular material
      - npm install --save @angular/material@8.2.3
      - ls -alrt node_modules/@angular/material
  build: 
    commands: 
      - echo Build started on `date` 
      - ng build --prod --base-href ./
      - echo checking the content of prod
      - ls -alrt prod/
  post_build: 
    commands: 
      - echo Build completed on `date` 
# Include only the files required for your application to run. 
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages  
# used only for building and testing. 
# ExpressJS apps will need other artifact directories included (bin/  *, pu blic/*, routes/*, views/* etc). 
artifacts: 
  files: 
    - '**/*'
  base-directory: 'dist/client'
 