const responseHelper = require('../Helper/commonHelper');
const mysqlLib = require('../config/database');

module.exports.createtask = function (database,task) {
    return new Promise(async (resolve, reject) => {
       try {
          let sql="INSERT INTO "+database+".task SET ? ";
          let query = mysqlLib.query(sql,task,(err, results) => {
            if(err){
               console.log(err);
               reject(err);
            }else
              resolve(results);
          })
       } catch (err) {
          resolve(responseHelper.generateError("Somthing went wrong", err));
       }
    });
 
 }
 
 module.exports.getalltask = function (database) {
    return new Promise(async (resolve, reject) => {
       try {
          let sql="select * from "+database+".task where autogenerated=0";
          let query = mysqlLib.query(sql,(err, results) => {
            if(err){
               console.log(err);
               reject(err);
            }else
              resolve(results);
          })
       } catch (err) {
          resolve(responseHelper.generateError("Somthing went wrong", err));
       }
    });
 
 }
 
 module.exports.isdonestatus = function (database,status,task_id) {
   return new Promise(async (resolve, reject) => {
      try {
         let sql="Update  "+database+".task SET ? where task_id=?";
         let query = mysqlLib.query(sql,[status,task_id],(err, results) => {
           if(err){
              console.log(err);
              reject(err);
           }else
             resolve(results);
         })
      } catch (err) {
         resolve(responseHelper.generateError("Somthing went wrong", err));
      }
   });

}

module.exports.taskstage = function (database,status,task_id) {
   return new Promise(async (resolve, reject) => {
      try {
         let sql="Update  "+database+".task SET ? where task_id=?";
         let query = mysqlLib.query(sql,[status,task_id],(err, results) => {
           if(err){
              console.log(err);
              reject(err);
           }else
             resolve(results);
         })
      } catch (err) {
         resolve(responseHelper.generateError("Somthing went wrong", err));
      }
   });

}

module.exports.getprojecttask = function (database,proj_id) {
   return new Promise(async (resolve, reject) => {
      try {
         let sql="select * from "+database+".task where project_id=?";
         let query = mysqlLib.query(sql,proj_id,(err, results) => {
           if(err){
              console.log(err);
              reject(err);
           }else
             resolve(results);
         })
      } catch (err) {
         resolve(responseHelper.generateError("Somthing went wrong", err));
      }
   });

}
module.exports.getprojectalltask = function (database) {
   return new Promise(async (resolve, reject) => {
      try {
         let sql="select * from "+database+".task where project_id!=NULL";
         let query = mysqlLib.query(sql,proj_id,(err, results) => {
           if(err){
              console.log(err);
              reject(err);
           }else
             resolve(results);
         })
      } catch (err) {
         resolve(responseHelper.generateError("Somthing went wrong", err));
      }
   });

}
module.exports.getprojectsallpendingtask = function (database) {
   return new Promise(async (resolve, reject) => {
      try {
         let sql="select * from "+database+".task where project_id!='NULL'";
         let query = mysqlLib.query(sql,(err, results) => {
           if(err){
              console.log(err);
              reject(err);
           }else
             resolve(results);
         })
      } catch (err) {
         resolve(responseHelper.generateError("Somthing went wrong", err));
      }
   });

}
module.exports.deletetask = function (database,task_id) {
   return new Promise(async (resolve, reject) => {
      try {
        
         var sql = "DELETE From "+database+".task WHERE task_id= ?"
         let query = mysqlLib.query(sql, task_id, (err, results) => {
            if (err) {
               reject(err);
            } else
               resolve(results);
         });

      } catch (err) {
         resolve(responseHelper.generateError("Somthing went wrong", err));

      }
   });

}

module.exports.getcurruntmonthtask = function (database) {
   return new Promise(async (resolve, reject) => {
      try {
         let sql="SELECT * FROM "+database+".task WHERE MONTH(created_date) = MONTH(CURRENT_DATE()) AND YEAR(created_date) = YEAR(CURRENT_DATE())";
         let query = mysqlLib.query(sql,(err, results) => {
           if(err){
              console.log(err);
              reject(err);
           }else
             resolve(results);
         })
      } catch (err) {
         resolve(responseHelper.generateError("Somthing went wrong", err));
      }
   });

}

module.exports.getcurruntyeartask = function (database) {
   return new Promise(async (resolve, reject) => {
      try {
         let sql="SELECT * FROM "+database+".task WHERE YEAR(created_date) = YEAR(CURRENT_DATE())";
         let query = mysqlLib.query(sql,(err, results) => {
           if(err){
              console.log(err);
              reject(err);
           }else
             resolve(results);
         })
      } catch (err) {
         resolve(responseHelper.generateError("Somthing went wrong", err));
      }
   });

}